apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  ports:
    - targetPort: 8008
      port: 80
      nodePort: 30000
      protocol: TCP
  selector:
    app: catalog